#!/usr/bin/env python
"""
Batch pipeline: generate CCPP-SCM DEPHY cases from ERA5 for Ameriflux sites.

Usage
-----
    python run_ameriflux_sites.py sites.csv \\
        --output_dir /scratch/my_cases \\
        --scm_cases_dir /path/to/scm/data/processed_case_input \\
        --scm_config_dir /path/to/scm/etc/case_config \\
        [--skip_download]   # re-use existing ERA5 files

Sites CSV format (no header required, but a header row is fine)
---------------------------------------------------------------
    site_id, lat, lon, start_date, end_date[, sfc_roughness_length_cm[, column_area]]

    US-MMS, 39.3232, -86.4131, 2019-06-01, 2019-09-01
    US-Ha1, 42.5378, -72.1715, 2019-06-01, 2019-09-01
    US-Whs, 31.7438, -110.0522, 2019-06-01, 2019-09-01

Output per site (in {output_dir}/{site_id}/)
--------------------------------------------
    {site_id}_pl.nc          — raw ERA5 pressure-level data
    {site_id}_sfc.nc         — raw ERA5 surface data
    {site_id}_SCM_driver.nc  — DEPHY-format SCM driver (copied to scm_cases_dir)
    {site_id}.nml            — SCM case-config namelist (copied to scm_config_dir)

After running this script, execute the SCM with:
    cd /path/to/scm/bin
    ./run_scm.py -f /path/to/scm_run_list.py --npz_type gfs
"""

import argparse
import csv
import os
import sys
import traceback
from pathlib import Path

# Ensure the package is importable when running from the scripts/ dir
_pkg_root = Path(__file__).resolve().parent.parent
if str(_pkg_root) not in sys.path:
    sys.path.insert(0, str(_pkg_root))

from era5_to_ccpp_scm.download_era5 import download_era5_time_series
from era5_to_ccpp_scm.cli import _core_convert_forcings, _core_convert_to_dephy


# ---------------------------------------------------------------------------
# Default site catalogue (override with a CSV file at runtime)
# ---------------------------------------------------------------------------

DEFAULT_SITES = [
    # site_id,   lat,      lon,       start_date,   end_date,    zorl_cm, area_m2
    ("US-MMS",  39.3232,  -86.4131,  "2019-06-01", "2019-09-01",  15.0,  145_000_000.0),
    ("US-Ha1",  42.5378,  -72.1715,  "2019-06-01", "2019-09-01",  15.0,  145_000_000.0),
    ("US-Whs",  31.7438, -110.0522,  "2019-06-01", "2019-09-01",  15.0,  145_000_000.0),
]

# GFS P8 suite name used to build the SCM run list
SCM_SUITE = "SCM_GFS_v17_p8_ugwpv1"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_sites(csv_path: str):
    """
    Load site definitions from a CSV file.

    Expected columns (in order, header optional):
        site_id, lat, lon, start_date, end_date
        [, sfc_roughness_length_cm  [, column_area]]
    """
    sites = []
    with open(csv_path, newline="") as fh:
        reader = csv.reader(fh)
        for row in reader:
            row = [c.strip() for c in row]
            if not row or row[0].startswith("#"):
                continue
            # Skip a header row that starts with a non-numeric first field
            if row[0].lower() in ("site_id", "site", "name", "id"):
                continue
            if len(row) < 5:
                print(f"  [warn] Skipping short row: {row}", file=sys.stderr)
                continue
            site_id    = row[0]
            lat        = float(row[1])
            lon        = float(row[2])
            start_date = row[3]
            end_date   = row[4]
            zorl_cm    = float(row[5]) if len(row) > 5 else 15.0
            column_area = float(row[6]) if len(row) > 6 else 145_000_000.0
            sites.append((site_id, lat, lon, start_date, end_date, zorl_cm, column_area))
    return sites


def _write_scm_run_list(run_list_path: str, site_ids: list, suite: str = SCM_SUITE):
    """Write a run_list Python file consumable by run_scm.py -f."""
    lines = [
        "# Auto-generated by run_ameriflux_sites.py",
        "# Usage: ./run_scm.py -f <this_file> --npz_type gfs",
        "",
        "run_list = [",
    ]
    for site_id in site_ids:
        lines.append(f'    {{"case": "{site_id}", "suite": "{suite}"}},')
    lines += ["]", ""]
    with open(run_list_path, "w") as fh:
        fh.write("\n".join(lines))
    print(f"\nSCM run list written to: {run_list_path}")
    print(f"Run with:  ./run_scm.py -f {run_list_path} --npz_type gfs")


# ---------------------------------------------------------------------------
# Per-site pipeline
# ---------------------------------------------------------------------------

def process_site(
    site_id, lat, lon, start_date, end_date,
    output_dir,
    sfc_roughness_length_cm=15.0,
    column_area=145_000_000.0,
    template="gabls3",
    skip_download=False,
    scm_cases_dir=None,
    scm_config_dir=None,
):
    site_dir = os.path.join(output_dir, site_id)
    os.makedirs(site_dir, exist_ok=True)

    era5_pl_file  = os.path.join(site_dir, f'{site_id}_pl.nc')
    era5_sfc_file = os.path.join(site_dir, f'{site_id}_sfc.nc')
    dephy_file    = os.path.join(site_dir, f'{site_id}_SCM_driver.nc')
    nml_file      = os.path.join(site_dir, f'{site_id}.nml')

    # Step 1 — Download ERA5
    if skip_download and os.path.exists(era5_pl_file) and os.path.exists(era5_sfc_file):
        print(f"  [skip_download] Using existing ERA5 files for {site_id}")
    else:
        print(f"  Downloading ERA5 for {site_id} ({lat:.4f}N, {lon:.4f}E) "
              f"{start_date} → {end_date}")
        download_era5_time_series(
            start_date=start_date,
            end_date=end_date,
            lat=lat,
            lon=lon,
            output_dir=site_dir,
            name=site_id,
        )

    # Step 2 — Convert forcings
    print(f"  Converting ERA5 forcings for {site_id}")
    era5_processed = _core_convert_forcings(era5_sfc_file, era5_pl_file)

    # Step 3 — Write DEPHY + namelist
    print(f"  Writing DEPHY case for {site_id}")
    _core_convert_to_dephy(
        era5_processed_forcings=era5_processed,
        start_date=start_date,
        case_name=site_id,
        output_file=dephy_file,
        template=template,
        column_area=column_area,
        sfc_roughness_length_cm=sfc_roughness_length_cm,
        namelist_file=nml_file,
        scm_cases_dir=scm_cases_dir,
        scm_config_dir=scm_config_dir,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Batch ERA5 → CCPP-SCM DEPHY pipeline for Ameriflux sites",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "sites_csv", nargs="?", default=None,
        help="CSV file with site definitions (see docstring for format). "
             "If omitted, the built-in DEFAULT_SITES list is used.",
    )
    parser.add_argument("--output_dir", default="./scm_cases",
                        help="Root directory for all output (default: ./scm_cases)")
    parser.add_argument("--scm_cases_dir", default=None,
                        help="If set, install *_SCM_driver.nc files here "
                             "(e.g. scm/data/processed_case_input)")
    parser.add_argument("--scm_config_dir", default=None,
                        help="If set, install *.nml files here "
                             "(e.g. scm/etc/case_config)")
    parser.add_argument("--template", default="gabls3",
                        help="Template name for static fields (default: gabls3)")
    parser.add_argument("--suite", default=SCM_SUITE,
                        help=f"Physics suite for the SCM run list "
                             f"(default: {SCM_SUITE})")
    parser.add_argument("--run_list", default=None,
                        help="Path to write the SCM run-list .py file. "
                             "If omitted, written to {output_dir}/scm_run_list.py")
    parser.add_argument("--skip_download", action="store_true",
                        help="Re-use existing ERA5 files if present")
    parser.add_argument("--sites", nargs="+", default=None,
                        help="Process only these site IDs (space-separated)")
    args = parser.parse_args()

    # Load site definitions
    if args.sites_csv:
        sites = _load_sites(args.sites_csv)
    else:
        sites = [
            (s[0], s[1], s[2], s[3], s[4], s[5], s[6])
            for s in DEFAULT_SITES
        ]

    # Filter to requested subset
    if args.sites:
        requested = set(args.sites)
        sites = [s for s in sites if s[0] in requested]
        if not sites:
            print(f"[error] No matching sites found for: {args.sites}", file=sys.stderr)
            sys.exit(1)

    print(f"Processing {len(sites)} site(s) → {args.output_dir}")
    if args.scm_cases_dir:
        print(f"  SCM cases dir:  {args.scm_cases_dir}")
    if args.scm_config_dir:
        print(f"  SCM config dir: {args.scm_config_dir}")
    print()

    successful = []
    failed = []

    for (site_id, lat, lon, start_date, end_date,
         sfc_roughness_length_cm, column_area) in sites:
        print(f"=== {site_id} ===")
        try:
            process_site(
                site_id=site_id,
                lat=lat,
                lon=lon,
                start_date=start_date,
                end_date=end_date,
                output_dir=args.output_dir,
                sfc_roughness_length_cm=sfc_roughness_length_cm,
                column_area=column_area,
                template=args.template,
                skip_download=args.skip_download,
                scm_cases_dir=args.scm_cases_dir,
                scm_config_dir=args.scm_config_dir,
            )
            successful.append(site_id)
            print(f"  [OK] {site_id}\n")
        except Exception:
            failed.append(site_id)
            print(f"  [FAILED] {site_id}", file=sys.stderr)
            traceback.print_exc()
            print()

    # Write SCM run list for successful sites
    run_list_path = args.run_list or os.path.join(args.output_dir, "scm_run_list.py")
    if successful:
        _write_scm_run_list(run_list_path, successful, suite=args.suite)

    # Summary
    print("\n=== Summary ===")
    print(f"  Succeeded: {len(successful)}/{len(sites)}")
    if failed:
        print(f"  Failed:    {', '.join(failed)}")
    if successful:
        print(f"\nNext step:")
        print(f"  cd <scm>/bin")
        print(f"  ./run_scm.py -f {run_list_path} --npz_type gfs")

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
